language: generic 
sudo : required
services:
  - docker

before_install:
  - docker build -t kra5io/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test